Fix build issues
twilio/sync-quickstart-android pull request #9
Opened 2021-01-08 17:18 UTC by jefflinwood

Updated the project to build with Android Studio 4.1 - AndroidX and Gradle updates.

Removed Fabric and Crashlytics (they are no longer supported)

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [X ] I acknowledge that all my contributions will be made under the project's license.

2021-01-08 18:10 UTC, micaswyers approved these changes

2021-01-08 18:10 UTC, micaswyers approved these changes

2021-01-11 07:58 UTC, rusmonster requested changes
The "Use AndroidX" commit contains only 1 empty file. Please fix.

2021-01-11 07:58 UTC, rusmonster commented on sync-quickstart-android/build.gradle
> -    implementation 'com.crashlytics.sdk.android:crashlytics:2.10.1'
we need crashlytics, why do you remove it?

2021-01-11 08:32 UTC, rusmonster commented on sync-quickstart-android/build.gradle
> -    implementation 'com.crashlytics.sdk.android:crashlytics:2.10.1'
Probably we should update it instead of removing. We even have a ticket about that: RTDSDK-2145 Feel free to take it.

2021-01-11 10:32 UTC, berkus requested changes
Pls don't remove crashlytics - this  is an example for customers on how to set it up for their projects. See RTDSDK-2145 and update it to the latest google version instead.

2021-01-11 15:37 UTC, jefflinwood commented
I'll update this PR to include Firebase Crashlytics, instead of just removing the obsolete/no longer builds Fabric Crashlytics. So don't merge it just yet.

2021-01-18 17:14 UTC, rusmonster commented
I've moved these changes in another PR together with migration to firebase crashlytics: https://github.com/twilio/sync-quickstart-android/pull/10

2021-01-18 17:14 UTC, closed without merging